baseURL: /
locale: en-us
default_Content_Language: en
build:
  writeStats: true
title: Vivien GACHET
# Uncomment below to use aafu as hugo theme. See instructions in README.md
# theme: aafu

params:
  author: Vivien Gachet
  description: site_pro
  copyright: powered by [hugo](https://gohugo.io/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  accordion:
    - item: about_me
      expand: true # only the first `expand: true` will take effect
    - item: experiences
    - item: education
    - item: publications
